### ISSUE TITLE
No longer able to log in

### ISSUE THREAD

**Issue by Barbaross93** [teegre/snotify#2]
I've unexpectedly been unable to login to snotify. My credentials are correct, as verified by logging into the spotify homepage. I'm not sure how it might of happened. Does snotify use gpg keys at all? That's the only thing that I think could be affected.

**Comment by teegre** [comment]
Hello! Sorry for the late reply and thank you for the feedback!

I experienced the same issue.

And it's related to the way **snotify** was obtaining an access token (relying on the **spotify-token** python module). So I got rid of the dependencies and simplified the code. From now on, **snotify** only displays a notification when needed but user's own client id and secret are required.

I made a new commit (details in the README file).
Tell me if it works for you.

Regards.

**Comment by Barbaross93** [comment]
Looks like its working for me again! Thanks a bunch
